services:
  mentorium:
    container_name: mentorium_back
    image: mentorium
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5129:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CLIENT_ID: 9061cd5e416f37e029f4
      CLIENT_SECRET: 9f4b7a018587a7277cdb3acf712da487269aa0cd
      DB_HOST: mentorium_db
      DB_PORT: 5432
      DB_NAME: mentorium
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  db:
    container_name: mentorium_db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentorium
    ports:
      - 5433:5432
