// <auto-generated />
using Mentorium;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mentorium.Migrations
{
    [DbContext(typeof(MentoriumDbContext))]
    [Migration("20240407145512_AddForeignKey")]
    partial class AddForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mentorium.Models.GithubUser", b =>
                {
                    b.Property<int>("GithubUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GithubUserId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GithubUserId");

                    b.HasIndex("UserId");

                    b.ToTable("GithubUsers");
                });

            modelBuilder.Entity("Mentorium.Models.MentorInfo", b =>
                {
                    b.Property<int>("MentorInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MentorInfoId"));

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MentorInfoId");

                    b.ToTable("MentorInfo");
                });

            modelBuilder.Entity("Mentorium.Models.MentorInfoStack", b =>
                {
                    b.Property<int>("MentorInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("MentoriumStackId")
                        .HasColumnType("integer");

                    b.HasKey("MentorInfoId", "MentoriumStackId");

                    b.HasIndex("MentoriumStackId");

                    b.ToTable("MentorInfoStacks");
                });

            modelBuilder.Entity("Mentorium.Models.MentoriumStack", b =>
                {
                    b.Property<int>("MentoriumStackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MentoriumStackId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MentoriumStackId");

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("Mentorium.Models.StudentInfo", b =>
                {
                    b.Property<int>("StudentInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentInfoId"));

                    b.HasKey("StudentInfoId");

                    b.ToTable("StudentInfo");
                });

            modelBuilder.Entity("Mentorium.Models.StudentInfoStack", b =>
                {
                    b.Property<int>("StudentInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("MentoriumStackId")
                        .HasColumnType("integer");

                    b.HasKey("StudentInfoId", "MentoriumStackId");

                    b.HasIndex("MentoriumStackId");

                    b.ToTable("StudentInfoStacksStack");
                });

            modelBuilder.Entity("Mentorium.Models.TelegramUser", b =>
                {
                    b.Property<int>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramUserId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TelegramUserId");

                    b.HasIndex("UserId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("Mentorium.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Descriotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MentorInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentInfoId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("MentorInfoId");

                    b.HasIndex("StudentInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mentorium.Models.GithubUser", b =>
                {
                    b.HasOne("Mentorium.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentorium.Models.MentorInfoStack", b =>
                {
                    b.HasOne("Mentorium.Models.MentorInfo", "MentorInfo")
                        .WithMany()
                        .HasForeignKey("MentorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentorium.Models.MentoriumStack", "MentoriumStack")
                        .WithMany()
                        .HasForeignKey("MentoriumStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentorInfo");

                    b.Navigation("MentoriumStack");
                });

            modelBuilder.Entity("Mentorium.Models.StudentInfoStack", b =>
                {
                    b.HasOne("Mentorium.Models.MentoriumStack", "MentoriumStack")
                        .WithMany()
                        .HasForeignKey("MentoriumStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentorium.Models.StudentInfo", "StudentInfo")
                        .WithMany()
                        .HasForeignKey("StudentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentoriumStack");

                    b.Navigation("StudentInfo");
                });

            modelBuilder.Entity("Mentorium.Models.TelegramUser", b =>
                {
                    b.HasOne("Mentorium.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentorium.Models.User", b =>
                {
                    b.HasOne("Mentorium.Models.MentorInfo", "MentorInfo")
                        .WithMany()
                        .HasForeignKey("MentorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentorium.Models.StudentInfo", "StudentInfo")
                        .WithMany()
                        .HasForeignKey("StudentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentorInfo");

                    b.Navigation("StudentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
